---
- name: Setup OpenStack services (Keystone, Nova, Swift, Trove, etc.)
  hosts: vagrant
  become: true

  vars_files:
    - vars/global.yml

  tasks:
    - import_tasks: tasks/base_setup.yml

    - name: Setup Keystone
      import_tasks: tasks/keystone.yml

    - name: Setup Nova
      import_tasks: tasks/nova.yml

    - name: Setup Swift
      import_tasks: tasks/swift.yml

    - name: Setup Trove
      import_tasks: tasks/trove.yml
    
    - name: Setup Ceilometer
      import_tasks: tasks/ceilometer.yml
    
    - name: Setup Neutron
      import_tasks: tasks/neutron.yml
