---
- name: Update APT package index
  apt:
    update_cache: yes
    cache_valid_time: 36000

- name: Install core packages (system essentials and tools)
  apt:
    name:
      - git
      - sudo
      - net-tools
      - curl
      - build-essential
      - python3-dev
      - libpython3-dev
      - python3-setuptools
      - libffi-dev
      - libxslt1-dev
      - libxml2-dev
      - libyaml-dev
      - libssl-dev
      - zlib1g-dev
      - mariadb-client
      - libmariadb-dev
    state: present

- name: Install OpenStack and related services packages
  apt:
    name:
      - python3-openstackclient
      - mariadb-server
      - rabbitmq-server
      - memcached
      - etcd
      - chrony
      - crudini
      - net-tools
      - apache2
      - libapache2-mod-wsgi-py3
    state: present

- name: Ensure MariaDB is installed (redundant check for idempotence)
  apt:
    name: mariadb-server
    state: present

- name: Ensure python3-pip is installed
  apt:
    name: python3-pip
    state: present

- name: Download get-pip.py
  ansible.builtin.get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    mode: "0755"
  register: download_getpip

- name: Install pip version 25.0.1 using get-pip.py
  ansible.builtin.command: python3 /tmp/get-pip.py pip==25.0.1
  args:
    creates: /usr/local/bin/pip
  become: true
  register: pip_install_result
  changed_when: "'Successfully installed pip' in pip_install_result.stdout or pip_install_result.rc == 0"

- name: Remove get-pip.py after installation
  ansible.builtin.file:
    path: /tmp/get-pip.py
    state: absent

- name: Ensure PyMySQL is installed for Ansible MySQL modules
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3
  become: true

- name: Install virtualenv locally for the non-root user
  ansible.builtin.pip:
    name: virtualenv
    executable: pip3
    extra_args: --user
  become: false

- name: Re-install build and Python3 dependencies (if not already present)
  apt:
    name:
      - build-essential
      - python3-dev
      - libpython3-dev
      - python3-setuptools
      - python3-pip
      - libffi-dev
      - libxslt1-dev
      - libxml2-dev
      - libyaml-dev
      - libssl-dev
      - zlib1g-dev
      - mariadb-client     
      - libmariadb-dev      
      - git
    state: present
    update_cache: yes
  become: true