---
- name: Update APT package index
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install basic packages
  apt:
    name:
      - git
      - python3-pip
      - sudo
      - net-tools
    state: present

- name: Install OpenStack and related services
  apt:
    name:
      - python3-openstackclient
      - mariadb-server
      - rabbitmq-server
      - memcached
      - etcd
      - chrony
      - crudini
      - net-tools
      - apache2
      - libapache2-mod-wsgi-py3
    state: present

- name: Ensure MariaDB is installed again (idempotent)
  apt:
    name: mariadb-server
    state: present

- name: Download get-pip.py
  ansible.builtin.get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    mode: "0755"

- name: Install pip version 25.0.1 using get-pip.py
  ansible.builtin.command: python3 /tmp/get-pip.py pip==25.0.1
  become: true

- name: Remove get-pip.py after installation
  ansible.builtin.file:
    path: /tmp/get-pip.py
    state: absent

- name: Ensure PyMySQL is installed for Ansible MySQL modules
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3
  become: true

- name: Install virtualenv locally for the user
  ansible.builtin.pip:
    name: virtualenv
    executable: pip3
    extra_args: --user
  become: false

- name: Ensure PyMySQL is installed for Ansible MySQL modules
  pip:
    name: PyMySQL

- name: Install build and Python3 dependencies
  apt:
    name:
      - build-essential
      - python3-dev
      - libpython3-dev
      - python3-setuptools
      - python3-pip
      - libffi-dev
      - libxslt1-dev
      - libxml2-dev
      - libyaml-dev
      - libssl-dev
      - zlib1g-dev
      - mysql-client
      - libmysqlclient-dev
      - git
    state: present
    update_cache: yes
  become: true

- name: Ensure curl is installed (required for get-pip)
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: yes
  become: true
