---
- name: Ensure 'keystone' database exists (via Unix socket with sudo)
  community.mysql.mysql_db:
    name: keystone
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create 'keystone'@'localhost' user with full privileges
  community.mysql.mysql_user:
    name: keystone
    host: localhost
    password: "{{ keystone_db_password }}"
    priv: "keystone.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create 'keystone'@'%' user with full privileges
  community.mysql.mysql_user:
    name: keystone
    host: "%"
    password: "{{ keystone_db_password }}"
    priv: "keystone.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
- name: Install Keystone
  apt:
    name: 
      - keystone
      - python3-keystoneclient
      - python3-keystonemiddleware
    state: present

- name: Set Keystone database connection string
  ansible.builtin.ini_file:
    path: /etc/keystone/keystone.conf
    section: database
    option: connection
    value: "mysql+pymysql://keystone:{{ keystone_db_password }}@controller/keystone"
    mode: '0640'
    backup: yes

- name: Set Keystone token provider to fernet
  ansible.builtin.ini_file:
    path: /etc/keystone/keystone.conf
    section: token
    option: provider
    value: "fernet"
    mode: '0640'
    backup: yes

- name: Run keystone-manage db_sync using sudo
  ansible.builtin.command: sudo keystone-manage db_sync
  become: true

- name: Initialize Fernet key repositories
  ansible.builtin.shell: |
    sudo keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
    sudo keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
  become: true

- name: Bootstrap the Keystone service
  ansible.builtin.shell: |
    sudo keystone-manage bootstrap \
      --bootstrap-password {{ os_admin_password }} \
      --bootstrap-admin-url http://{{ server_name }}:35357/v3/ \
      --bootstrap-internal-url http://{{ server_name }}:5000/v3/ \
      --bootstrap-public-url http://{{ server_name }}:5000/v3/ \
      --bootstrap-region-id RegionOne
  become: true

- name: Ensure 'ServerName controller' is set in apache2.conf
  ansible.builtin.lineinfile:
    path: /etc/apache2/apache2.conf
    line: "ServerName {{ server_name }}"
    insertafter: EOF
    state: present
  become: true

- name: Restart Apache2 service
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: true

