---
- name: Install Neutron packages
  ansible.builtin.apt:
    name:
      - neutron-server
      - neutron-plugin-ml2
      - neutron-linuxbridge-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
      - iptables
    state: present
    update_cache: yes
  become: true

- name: Ensure Neutron user exists
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack user show neutron >/dev/null 2>&1 \
      || openstack user create neutron --project service --password '{{ neutron_password }}'
  args:
    executable: /bin/bash
  become: true

- name: Ensure Neutron user has admin role on service project
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack role assignment list --user neutron --project service --names \
      | grep -qw admin \
      || openstack role add --user neutron --project service admin
  args:
    executable: /bin/bash
  become: true

- name: Ensure Neutron service is registered in Keystone
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack service show neutron >/dev/null 2>&1 \
      || openstack service create --name neutron \
         --description "OpenStack Networking" network
  args:
    executable: /bin/bash
  become: true

- name: Ensure Gnocchi user exists
  vars:
    gnocchi_password: YOUR_GNOCCHI_PASSWORD
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack user show gnocchi >/dev/null 2>&1 \
      || openstack user create --domain default \
         --password "{{ gnocchi_password }}" gnocchi
  args:
    executable: /bin/bash
  become: true

- name: Ensure Gnocchi service is registered in Keystone
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack service show gnocchi >/dev/null 2>&1 \
      || openstack service create --name gnocchi \
         --description "Metric Service" metric
  args:
    executable: /bin/bash
  become: true

- name: Ensure Gnocchi user has admin role on service project
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack role assignment list --project service --user gnocchi --names \
      | grep -qw admin \
      || openstack role add --project service --user gnocchi admin
  args:
    executable: /bin/bash
  become: true


- name: Create Neutron public endpoint
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack endpoint create --region RegionOne network public http://{{ neutron_api_host }}:9696
  args:
    executable: /bin/bash
  become: true

- name: Create Neutron admin endpoint
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack endpoint create --region RegionOne network admin http://{{ neutron_api_host }}:9696
  args:
    executable: /bin/bash
  become: true

- name: Create Neutron internal endpoint
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack endpoint create --region RegionOne network internal http://{{ neutron_api_host }}:9696
  args:
    executable: /bin/bash
  become: true



