---
- name: Install Swift and required packages
  ansible.builtin.apt:
    name:
      - swift
      - python3-swiftclient
      - swift-proxy
      - swift-account
      - swift-container
      - swift-object
    state: present
    update_cache: yes
  become: true

- name: Ensure Swift user exists
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack user show swift >/dev/null 2>&1 \
      || openstack user create swift --project service --password '{{ swift_password }}'
  args:
    executable: /bin/bash

- name: Ensure Swift user has admin role on service project
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack role assignment list --user swift --project service --names \
      | grep -qw admin \
      || openstack role add --user swift --project service admin
  args:
    executable: /bin/bash

- name: Ensure Swift service is registered in Keystone
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack service show swift >/dev/null 2>&1 \
      || openstack service create --name swift \
          --description "OpenStack Object Storage" object-store
  args:
    executable: /bin/bash

- name: Create Swift public endpoint
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack endpoint create --region RegionOne object-store public http://{{ swift_api_host }}:8080/v1/AUTH_
  args:
    executable: /bin/bash
  become: true

- name: Create Swift internal endpoint
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack endpoint create --region RegionOne object-store internal http://{{ swift_api_host }}:8080/v1/AUTH_
  args:
    executable: /bin/bash
  become: true

- name: Create Swift admin endpoint
  ansible.builtin.shell: |
    source /root/admin-openrc
    openstack endpoint create --region RegionOne object-store admin http://{{ swift_api_host }}:8080/v1
  args:
    executable: /bin/bash
  become: true